version: "3.3"

services:

  traefik:
    image: "traefik"
    restart: always
    container_name: "treafik_traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    restart: always
    container_name: "treafik_simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`treafik.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      
  mariadb:
    image: "mariadb"
    restart: always
    container_name: "treafik_mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
      TZ: "Europe/Brussels"
    volumes:
      - ./db/conf:/etc/mysql
      - ./db/log:/var/log/mysql
      - ./db/data:/var/lib/mysql
      
  wordpress:
    image: "wordpress"
    restart: always
    environment:
      VIRTUAL_HOST: "wp.localhost"
      WORDPRESS_DB_HOST: "treafik_mariadb:3306"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      TZ: "Europe/Brussels"
    container_name: "treafik_wordpress"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.localhost`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
    volumes:
      - ./wordpress:/var/www/html
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: "1"
      TZ: "Europe/Brussels"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
      
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - CLI_ARGS= #optional
      - TZ= Europe/Brussels
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.localhost`)"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.tls.certresolver=myresolver"
      - "traefik.port=8200"
    volumes:
      - path_to_docker_folder:/data
      - path_to_backup_docker_folder:/backuplocation
      
  dbBackup:
    image: fradelg/mysql-cron-backup
    restart: always
    volumes:
      - ./dbbackup:/backup
    environment:
      - MYSQL_USER=wordpress
      - MYSQL_PASS=wordpress
      - MYSQL_DB=wordpress
      - CRON_TIME=0 0 0 * * ? #every day at midnight
      - MYSQL_HOST=treafik_mariadb
      - MYSQL_PORT=3306
      - MAX_BACKUPS=10
      - TIMEOUT=10s
      - INIT_BACKUP=1
      - TZ=Europe/Brussels
  
  softethervpn:
    image: siomiz/softethervpn
    restart: always
    environment:
      - TZ= Europe/Brussels
    volumes:
      - ./vpn_server.config:/usr/vpnserver/vpn_server.config
    cap_add:
      - NET_ADMIN
    ports:
      - 500:500/udp #L2TP/IPSec
      - 4444:443/udp #softhether management
      - 4500:4500/udp #L2TP/IPSec
      - 1701:1701/tcp #L2TP/IPSec
      - 1194:1194/udp #openvpn
      - 5555:5555/tcp #softhether vpn
